"""Application-wide constants (non-secret)."""

from __future__ import annotations

import json
from pathlib import Path

APP_VERSION = "3.3.5.5.8.5.26.2"
APP_CODENAME = "Domain-Agnostic Japanese Accuracy & Audio Delivery Gate"
FROZEN_INFRASTRUCTURE_BASELINE = "3.3.5.5.8.5.25.3.3.2.8"

CANONICAL_TRANSCRIPT_LEDGER_ENABLED = True
SINGLE_REVISION_AUTHORITY_ENABLED = True
ATOMIC_STOP_FINALIZATION_BARRIER_ENABLED = True
FINAL_EXPORT_FROM_FROZEN_LEDGER_ONLY = True
RAW_EVENT_LINEAGE_REQUIRED = True
FAIL_CLOSED_PIPELINE_VALIDATION = True
DETERMINISTIC_REFERENCE_SNAPSHOT_ENABLED = True
LIVE_RUNTIME_METRICS_REGISTRY_ENABLED = True
CURRENT_RUN_ARTIFACT_ISOLATION_ENABLED = True
CRITICAL_GATE_PARTIAL_PASS_DISABLED = True

SAFE_STABLE_REVISION_ENABLED = True
REVISION_LINEAGE_REQUIRED = True
REVISION_TERMINAL_SENTENCE_GUARD_ENABLED = True
REVISION_CONTENT_LOSS_GUARD_ENABLED = True
UNPROVEN_REVISION_DEFAULT_ACTION = "append"
CER_OPERATION_ACCOUNTING_STRICT = True
RUNTIME_AUDIO_DELIVERY_COUNTERS_ENABLED = True

# Central troubleshooting evidence folder — all runtime logs under troubleshooting/
TROUBLESHOOTING_MODE = True
CENTRALIZED_TROUBLESHOOTING_DIR = True
FULL_DIAGNOSTIC_LOGGING_ENABLED = True
PENDING_RUN_REBINDING_ENABLED = True
EVIDENCE_SAFE_MODE = True
STARTUP_RECOVERY_MODE = True
STRICT_STARTUP_NON_BLOCKING_LOGGING = True
BLOCKING_EVIDENCE_ASSERTS_DURING_START_DISABLED = True
PENDING_WRITER_FAILURE_IS_WARNING_DURING_START = True
HIGH_FREQUENCY_UI_DRAIN_LOGGING_ENABLED = False
DEFER_VALIDATION_UNTIL_AFTER_STOP = True
DEFER_UPLOAD_PACKAGE_UNTIL_AFTER_STOP = True
UI_EVENT_DRAIN_VERBOSE_LOGGING = False
UI_EVENT_DRAIN_SAMPLE_INTERVAL_SECONDS = 30
STOP_FINALIZE_TWO_PHASE_MODE = True
STOP_CORE_NEVER_BLOCKS_ON_EVIDENCE = True
SINGLE_RUN_IDENTITY_LOCK_ENABLED = True
EVIDENCE_PACKAGE_WORKER_DEFERRED = True
RUN_ARTIFACTS_INDEX_NON_BLOCKING = True
STOP_FINALIZE_HARD_TIMEOUTS_ENFORCED = True
RUN_ID_MISMATCH_AUTO_REPAIR_ENABLED = True
RUNTIME_EVIDENCE_PACKAGE_DISABLED = True
OFFLINE_EVIDENCE_PACKAGING_ENABLED = True
STOP_PATH_MINIMAL_MODE = True
STOP_UI_RECOVERY_GUARANTEED = True
NO_UPLOAD_ZIP_DURING_RUNTIME = True
NO_VALIDATION_DURING_RUNTIME_STOP = True
NO_RUN_ARTIFACTS_REWRITE_DURING_STOP = True
NO_PENDING_MIGRATION_DURING_STOP = True
NO_WRITER_REGISTRY_SCAN_DURING_STOP = True

# Temporary audio buffer for debugging (auto-deleted after retention)
AUDIO_TEMP_CAPTURE_ENABLED = True
AUDIO_TEMP_RETENTION_HOURS = 2
AUDIO_TEMP_MAX_TOTAL_GB = 3
AUDIO_TEMP_CHUNK_SECONDS = 60
AUDIO_TEMP_INCLUDE_IN_UPLOAD_ZIP = False
TEMP_AUDIO_RETENTION_ENABLED = True
TEMP_AUDIO_RETENTION_HOURS = 2
TEMP_AUDIO_AUTO_DELETE_ENABLED = True
TEMP_AUDIO_INCLUDE_IN_UPLOAD_PACKAGE = False

# Log rotation for JSONL / high-volume evidence
LOG_ROTATION_ENABLED = True
LOG_MAX_FILE_MB = 50
LOG_ROTATION_BACKUPS = 5
RAW_INTERIM_LOG_SAMPLING_ENABLED = True
RAW_INTERIM_LOG_SAMPLE_RATE = 20
DEBUG_VERBOSE_INTERIMS = False

# Long-session stability — health snapshots and crash forensics (preserved from 8.5.17)
LONG_SESSION_STABILITY_MODE = True

# Tk-safe pipeline — background threads never call Tkinter; UI never blocks on assembler locks
TK_SAFE_PIPELINE_MODE = True
LANGUAGE_AGNOSTIC_UI_EVENT_BUS = True
FORBID_BACKGROUND_TK_CALLS = True
FORBID_UI_BLOCKING_LOCK_WAIT = True

# Long-run evidence package — auto-collect logs/artifacts for upload after test
LONG_RUN_EVIDENCE_PACKAGE_MODE = True

# Background partial autosave cadence (off UI thread)
PARTIAL_ALPHA_AUTOSAVE_INTERVAL_S = 30.0
PARTIAL_ALPHA_AUTOSAVE_COMMIT_INTERVAL = 25
PARTIAL_INDEX_AUTOSAVE_INTERVAL_S = 60.0
PARTIAL_INDEX_AUTOSAVE_COMMIT_INTERVAL = 50
LONG_SESSION_HEALTH_HEARTBEAT_INTERVAL_S = 30.0
HEALTH_TIMELINE_INTERVAL_S = 30.0

# Deepgram visibility defaults (Japanese effective timing — logging/diagnostics only).
# Runtime stream timing authority: alpha.stt_settings / alpha.config (JA 500/1500).
from alpha.stt_settings import (  # noqa: E402
    DEEPGRAM_JA_DIAGNOSTIC_ENDPOINTING_MS as DEEPGRAM_ENDPOINTING_MS,
    DEEPGRAM_JA_DIAGNOSTIC_UTTERANCE_END_MS as DEEPGRAM_UTTERANCE_END_MS,
    DEEPGRAM_MODEL as _STT_DEEPGRAM_MODEL,
)

DEEPGRAM_MODEL = _STT_DEEPGRAM_MODEL
DEEPGRAM_LANGUAGE = "ja"
DEEPGRAM_INTERIM_RESULTS = True
DEEPGRAM_PUNCTUATE = True
DEEPGRAM_SMART_FORMAT = True

# Startup / UI responsiveness
PERFORMANCE_SAFE_LOGGING = True
UI_PERFORMANCE_MODE = True
DEBUG_UI_LOOP_VERBOSE = False
DEBUG_AFTER_LOOP_VERBOSE = False
DEBUG_DIAGNOSTICS_VERBOSE = False
LOG_PREVIEW_MAX_CHARS = 120
MAX_LOG_PREVIEW_CHARS = 120
INTERIM_LOG_THROTTLE_MS = 1000
UI_QUEUE_POLL_MS = 100
UI_UPDATE_INTERVAL_MS = 100
UI_MAX_UPDATES_PER_TICK = 6
UI_QUEUE_TIME_BUDGET_MS = 10
UI_QUEUE_DEFER_MS = 10
TRANSCRIPT_UI_BATCH_FLUSH_MS = 200
TRANSCRIPT_UI_SCROLL_MAX_HZ = 4
INTERIM_UI_THROTTLE_MS = 200
DEFER_LOGO_MS = 600
DEFER_WAVEFORM_DRAW_MS = 400
UI_LAG_MONITOR_ENABLED = False
UI_LAG_MONITOR_INTERVAL_MS = 250
UI_LAG_WARN_MS = 250
UI_LAG_SEVERE_MS = 1000
UI_LAG_LOG_THROTTLE_MS = 1000
RESIZE_DEBOUNCE_MS = 200
TRANSCRIPT_RENDER_DEBOUNCE_MS = 100
CJK_CLEANUP_MAX_CHARS = 1000
CJK_REPEAT_SCAN_MAX_UNIT = 32
CJK_CLEANUP_SLOW_MS = 20

# When True, verbose NDJSON diagnostics ([LATENCY], [AUDIO_FORMAT], [INTERIM], etc.)
DEBUG_DIAGNOSTICS = False

# When True, Teams-focused quality diagnostics ([TEAMS_DIAG], etc.)
DEBUG_TEAMS_DIAGNOSTICS = False

# Teams source gate thresholds (RMS scale matches existing mixer readings)
MIC_ACTIVE_RMS_MIN = 80.0
SYSTEM_ACTIVE_RMS_MIN = 80.0
MIC_NOISE_MULTIPLIER = 4.0
SYSTEM_NOISE_MULTIPLIER = 3.0
MIC_TO_SYSTEM_RATIO_MIN = 0.08
OVERLAP_CONFIRM_FRAMES = 3
SOURCE_HOLD_MS = 500

# Meeting segment buffer (disabled in restore mode)
MEETING_SEGMENT_BUFFER_ENABLED = False
MEETING_BUFFER_MAX_GAP_MS = 1500
MEETING_BUFFER_MAX_HOLD_MS = 2500
MEETING_BUFFER_MIN_FRAGMENT_WORDS = 3
MEETING_BUFFER_FLUSH_ON_SPEAKER_CHANGE = True
MEETING_BUFFER_FLUSH_ON_SOURCE_CHANGE = True
MEETING_BUFFER_ENABLE_OVERLAP_MERGE = True

# Retrospective segment repair
MEETING_SEGMENT_REPAIR_ENABLED = False
MEETING_SEGMENT_REPAIR_MAX_GAP_MS = 6000

# Auto-language gate disabled in Japanese foundation mode
AUTO_LANGUAGE_ENABLED = False
DEFAULT_SOURCE_LANGUAGE = "ja"
FORCE_DEEPGRAM_LANGUAGE = "ja"
LANGUAGE_CONFIDENCE_SAFE = 0.70
LANGUAGE_CONFIDENCE_UNSTABLE = 0.45
LANGUAGE_CONFIDENCE_REJECT = 0.45
LANGUAGE_GATE_ENABLED = False
LANGUAGE_GATE_BLOCKING_MODE = False
LANGUAGE_GATE_WARNING_ONLY = False

# UI label retained for compatibility
AUTO_SOURCE_LANGUAGE_UI = "Auto: English + Japanese"

JAPANESE_MODE_ENABLED = True
JAPANESE_TEXT_NORMALIZATION_ENABLED = True
JAPANESE_CHAR_DEDUP_ENABLED = True
JAPANESE_INTERNAL_REPEAT_REMOVAL_ENABLED = True
JAPANESE_PARTIAL_OVERLAP_REMOVAL_ENABLED = True
JAPANESE_TAIL_STITCH_ENABLED = True
JAPANESE_SAFE_MERGE_GUARD_ENABLED = True
JAPANESE_PREFIX_REPEAT_REMOVAL_ENABLED = True
JAPANESE_COMPOUND_CONTINUATION_ENABLED = True
JAPANESE_KNOWN_TERM_CORRECTION_ENABLED = False
JAPANESE_GUARDED_KNOWN_CORRECTIONS_ENABLED = False
CJK_CLEANUP_ENABLED = True
CJK_LOCAL_REPEAT_FIX_ENABLED = True
CJK_PREFIX_OVERLAP_FIX_ENABLED = True
CJK_BOUNDARY_PUNCTUATION_FIX_ENABLED = True
CJK_POST_MERGE_CLEANUP_ENABLED = True
JAPANESE_KEYTERMS_ENABLED = True
JAPANESE_KEYTERM_MAX = 100
JAPANESE_KEYTERM_PROFILE = "business_japanese"
# Accuracy profiles — inactive in production; orchestrator sets env to activate.
JAPANESE_ACCURACY_PROFILE = ""
ACCURACY_PROFILE_TARGET_85_MEETING_CONTEXT = "target_85_meeting_context"
ACCURACY_PROFILE_DOMAIN_AGNOSTIC_NO_HINTS = "domain_agnostic_no_hints"
# test01_meeting_context remains experimental_only; never production or multidomain default.
TEST01_MEETING_CONTEXT_STATUS = "experimental_only"
TEST01_MEETING_CONTEXT_PRODUCTION_ENABLED = False
TEST01_MEETING_CONTEXT_MULTIDOMAIN_BENCHMARK_ALLOWED = False
BENCHMARK_AUDIO_SOURCE = ""
ISSUE12_STAGE1_MEETING_CONTEXT_GLOSSARY_PATH = (
    "troubleshooting/accuracy_benchmark/glossaries/test01_meeting_context.json"
)
KEYTERM_PROFILE_NEUTRAL = "neutral"
KEYTERM_PROFILE_BUSINESS_JAPANESE = "business_japanese"
KEYTERM_PROFILE_ESL_TWICE_TEST = "esl_twice_test"
JAPANESE_STABLE_ACCURACY_FIX_ENABLED = True
RAW_DEEPGRAM_IMMUTABLE = True
STABLE_LAYER_SAFE_MERGE_ENABLED = True
PUNCTUATION_START_MERGE_ENABLED = True
INCOMPLETE_TAIL_HOLD_ENABLED = True
BUSINESS_PHRASE_PROTECTION_ENABLED = True
ASSEMBLER_EXCEPTION_NO_DIRECT_COMMIT = True
TRANSLATION_READINESS_METRICS_ENABLED = True
JAPANESE_BUSINESS_ACCURACY_8522_ENABLED = True
ACCURACY_EVIDENCE_MODE_ENABLED = True
AUTO_EXPORT_ALPHA_TXT_ENABLED = True
AUTO_EXPORT_ALPHA_TXT_ON_STOP = True
STABLE_LAYER_BUSINESS_CORRECTION_ENABLED = True
STOP_TAIL_CLEANUP_ENABLED = True
SUPPRESS_INCOMPLETE_STOP_TAIL_FROM_ALPHA = True
WRITE_INCOMPLETE_STOP_TAIL_TO_DEBUG_FILE = True
SHOW_INCOMPLETE_STOP_TAIL = False
BUSINESS_CORRECTION_GUARD_85221_ENABLED = True
BUSINESS_CORRECTION_IDEMPOTENT_MODE = True
PUNCTUATION_START_POST_CORRECTION_MERGE_ENABLED = True
STOP_TAIL_VALIDATION_NA_FIX_ENABLED = True
FINAL_UI_UPDATE_TIMED_OUT_KWARG_FIX_ENABLED = True
FULL_ACCURACY_LOGGING_STILL_ENABLED = True
BUSINESS_ACCURACY_EXPANSION_85222_ENABLED = False
ACCURACY_REGRESSION_ROLLBACK_85223_ENABLED = True
SAFE_CORRECTION_GATE_ENABLED = True
DISABLE_HARMFUL_85222_EXPANSION_RULES = True
DISABLE_POLITE_CLOSING_ZO_PREFIX = True
STRICT_IDEMPOTENT_CORRECTIONS_ONLY = True
EVIDENCE_POINTER_FIXES_FROM_85222_PRESERVED = True
ACCURACY_BASELINE_85221_PRESERVED = True
ACCURACY_DIRECTION_SETTLED = True
BENCHMARK_BASELINE_LOCK_ENABLED = True
ANTI_OVERFIT_MODE_ENABLED = True
LESSON_SPECIFIC_CORRECTIONS_DISABLED = True
AUTO_BUSINESS_CORRECTION_LEVEL = "minimal_plus_user_glossary"
CORRECTION_RULE_APPROVAL_REQUIRED = True
SINGLE_SAMPLE_CORRECTION_BLOCKED = True
REFERENCE_SCORING_REQUIRED_FOR_NEW_RULES = True
EVIDENCE_PROTECTION_85232_ENABLED = True
REAL_LIVE_ALPHA_PROTECTION_ENABLED = True
SMOKE_TEST_ALPHA_OVERWRITE_BLOCKED = True
VISIBLE_ERROR_AUDIT_EXPANDED = True
REFERENCE_TRANSCRIPT_QUALITY_CHECK_ENABLED = True
CER_REFERENCE_VALIDATION_ENABLED = True
REFERENCE_ALIGNMENT_DIAGNOSIS_ENABLED = True
JAPANESE_BOUNDARY_DIAGNOSIS_ENABLED = True
BUSINESS_TERM_RISK_REPORT_ENABLED = True
GLOSSARY_CANDIDATE_REPORT_ENABLED = True
REFERENCE_CLEANUP_SUGGESTIONS_ENABLED = True
BUSINESS_CER_BENCHMARK_INTEGRITY_ENABLED = True
REPORT_SYNCHRONIZATION_85234_ENABLED = True
CER_TRUST_REQUIRES_ALIGNMENT_COVERAGE = True
LATEST_ANALYZER_REPORT_SYNC_ENABLED = True
UPLOAD_PACKAGE_ANALYZER_REPORTS_ENABLED = True
BUSINESS_VIDEO_TEST_PROTOCOL_ENABLED = True
REFERENCE_ALPHA_HASH_BINDING_ENABLED = True
ALIGNMENT_COVERAGE_REPAIR_852341_ENABLED = True
PARAGRAPH_WINDOW_ALIGNMENT_ENABLED = True
SLIDING_TEXT_WINDOW_ALIGNMENT_ENABLED = True
CER_TRUST_ALIGNMENT_V2_ENABLED = True
EVIDENCE_INDEX_SYNC_AFTER_SCORING_ENABLED = True
LATEST_REPORT_SYNC_STRICT_MATCH_ENABLED = True
LINE_COUNT_MISMATCH_TOLERANCE_ENABLED = True
JAPANESE_BOUNDARY_STABILIZER_ENABLED = True
JAPANESE_BOUNDARY_STABILIZER_MODE = "safe_active"
JAPANESE_BOUNDARY_SHADOW_METRICS_ENABLED = True
JAPANESE_BOUNDARY_DECISION_LOG_ENABLED = True
JAPANESE_LEADING_FRAGMENT_HOLD_ENABLED = True
JAPANESE_SAFE_MERGE_ENABLED = True
JAPANESE_DUPLICATE_CONTINUATION_GUARD_ENABLED = True
JAPANESE_MIDLINE_PUNCTUATION_CLEANUP_ENABLED = True
JAPANESE_STOP_FLUSH_BOUNDARY_SAFE = True
BOUNDARY_STABILIZER_HOLD_MS_DEFAULT = 2500
BOUNDARY_STABILIZER_HOLD_MS_MAX = 4000
BOUNDARY_STABILIZER_SAFE_MERGE_MAX_CHARS = 160
BOUNDARY_STABILIZER_PENDING_MERGE_MAX_CHARS = 180
BOUNDARY_STABILIZER_LEADING_FRAGMENT_MAX_CHARS = 45
BOUNDARY_MERGE_REVISION_ENABLED = True
STABLE_LINE_REVISION_MODEL_ENABLED = True
CLEAN_ALPHA_EXPORT_ENABLED = True
CUMULATIVE_MERGE_DUPLICATE_GUARD_ENABLED = True
BOUNDARY_EXPORT_SOURCE_UI_SEGMENTS_ENABLED = True
BOUNDARY_REPORT_PACKAGE_FIX_ENABLED = True
BOUNDARY_SUMMARY_PATH_FIX_ENABLED = True
RESIDUAL_DUPLICATE_CLEANUP_ENABLED = True
PUNCTUATION_ARTIFACT_CLEANUP_ENABLED = True
FINAL_CLEAN_TRANSCRIPT_PERSISTENCE_ENABLED = True
STABLE_REVISION_HISTORY_PERSISTENCE_ENABLED = True
BOUNDARY_DECISIONS_FINALIZATION_ENABLED = True
BOUNDARY_EVIDENCE_PACKAGE_COMPLETION_ENABLED = True
CUMULATIVE_ALPHA_REJECTION_ENABLED = True
CLEAN_ALPHA_EXPORT_REQUIRED_FOR_SCORING = True
CORPORATE_IR_GLOSSARY_ENABLED = False
CORPORATE_IR_GLOSSARY_MODE = "user_provided_high_confidence"
CORPORATE_IR_GLOSSARY_PATH = "troubleshooting/accuracy_benchmark/glossaries/test01_corporate_ir_glossary.json"
GLOSSARY_KEYTERM_BOOST_ENABLED = True
GLOSSARY_KEYTERM_MAX = 150
STABLE_GLOSSARY_CORRECTION_ENABLED = True
STABLE_GLOSSARY_CORRECTION_MODE = "high_confidence_only"
FINANCIAL_NUMBER_AUDIT_ENABLED = True
FINANCIAL_NUMBER_CORRECTION_ENABLED = True
FINANCIAL_NUMBER_CORRECTION_MODE = "expected_value_context_only"
CORPORATE_TERM_AUDIT_ENABLED = True
NAME_COMPANY_AUDIT_ENABLED = True
GLOSSARY_CORRECTION_DECISION_LOG_ENABLED = True
LOSSLESS_CLEAN_EXPORT_ENABLED = True
EXPORT_COVERAGE_GATE_ENABLED = True
VALID_SEGMENT_LOSS_BLOCKER_ENABLED = True
CONSERVATIVE_DUPLICATE_SUPPRESSION_ENABLED = True
SUPPRESSION_DECISION_LOG_ENABLED = True
GLOSSARY_EVIDENCE_SYNC_FIX_ENABLED = True
SCORE_GLOSSARY_METADATA_SYNC_ENABLED = True
LATEST_INDEX_GLOSSARY_SYNC_FIX_ENABLED = True
CANONICAL_TRANSCRIPT_LINEAGE_ENABLED = True
FINAL_EXPORT_LOCK_ENABLED = True
SOURCE_COMMIT_LINEAGE_REQUIRED = True
LINEAGE_BASED_EXPORT_COVERAGE_ENABLED = True
PRE_CORRECTION_REENTRY_BLOCK_ENABLED = True
CORRECTED_LINE_REPRESENTS_SOURCE_ENABLED = True
TEXT_SIMILARITY_RECOVERY_SECONDARY_ONLY = True
CANONICAL_CLEAN_TRANSCRIPT_REQUIRED_FOR_SCORING = True
GLOSSARY_CORRECTION_LINEAGE_ENABLED = True
BOUNDARY_REVISION_LINEAGE_ENABLED = True
SUPPRESSION_AWARE_LINEAGE_COVERAGE_ENABLED = True
INTENTIONAL_SUPPRESSION_PROVENANCE_REQUIRED = True
FULL_SPAN_FINANCIAL_NUMBER_CORRECTION_ENABLED = True
FINANCIAL_NUMBER_SEMANTIC_VALIDATION_ENABLED = True
MALFORMED_NUMERIC_OUTPUT_BLOCK_ENABLED = True
CANONICAL_CORRECTION_LINEAGE_REQUIRED = True
CANONICAL_OUTPUT_ARTIFACT_UNIFICATION_ENABLED = True
ATOMIC_ACCURACY_EVIDENCE_FINALIZATION_ENABLED = True
THREE_STAGE_ACCURACY_DIAGNOSTIC_ENABLED = True
RAW_DEEPGRAM_STAGE_CAPTURE_ENABLED = True
ASSEMBLER_ONLY_STAGE_CAPTURE_ENABLED = True
FINAL_ALPHA_STAGE_CAPTURE_ENABLED = True
DEEPGRAM_REQUEST_SNAPSHOT_ENABLED = True
IMMUTABLE_LIVE_STAGE_EVIDENCE_ENABLED = True
THREE_STAGE_CER_SCORING_ENABLED = True
DIAGNOSTIC_STAGE_TEXT_MUTATION_ALLOWED = False
VALIDATION_MAY_WRITE_LATEST_LIVE_OUTPUT = False
EVIDENCE_POINTER_FINALIZATION_FIX_ENABLED = True
LATEST_POINTER_COMPLETED_STATUS_FIX_ENABLED = True
LATEST_UPLOAD_ZIP_POINTER_FIX_ENABLED = True
LATEST_ACCURACY_ZIP_FLUSH_FIX_ENABLED = True
JAPANESE_ACCURACY_MODE = True
LONG_TEST_BASELINE_MODE = True
JAPANESE_WEAK_PHRASE_HINTS_ENABLED = False
# Japanese continuity assembler owns buffering (V3.3.5.5.8.5+)
JAPANESE_CONTINUITY_ASSEMBLER_ENABLED = True
JAPANESE_CONTINUITY_ASSEMBLER_SAFE_MODE = True
JAPANESE_CONTINUITY_MAX_BUFFER_CHARS = 100
JAPANESE_CONTINUITY_MAX_PARTS = 12
JAPANESE_CONTINUITY_MAX_HOLD_MS = 8000
JAPANESE_EMERGENCY_LAST_FRAG_GRACE_MS = 3500
JAPANESE_NOISE_QUARANTINE_SILENCE_S = 15.0
JAPANESE_NOISE_QUARANTINE_MAX_COMPACT = 20
JAPANESE_NOISE_QUARANTINE_RELEASE_COMPACT = 25
JAPANESE_NOISE_QUARANTINE_DROP_S = 8.0
# Deepgram raw STT diagnostic profile: current | no_diarize | high_sample_rate_if_supported
JAPANESE_STT_PROFILE = "no_diarize"
# Short valid Japanese list/time terms — never drop as noise quarantine
VALID_SHORT_JAPANESE_LIST_TERMS = frozenset(
    {
        "このたび",
        "本日",
        "明日",
        "昨日",
        "先日",
        "翌日",
        "先ほど",
        "後ほど",
    }
)

JAPANESE_LIST_LESSON_CONTEXT_CUES = (
    "改まった表現",
    "時間に関する言葉",
    "発音",
    "表をご覧ください",
    "本日",
    "明日",
    "昨日",
    "先日",
    "先ほど",
    "後ほど",
    "翌日",
)

# ESL/TWICE test profile — explicit only, not default
JAPANESE_KEYTERMS_ESL_TWICE = [
    "ESL",
    "オンライン",
    "ディスカッション",
    "尊敬",
    "尊敬してる人",
    "誰ですかっていう質問",
    "トワイス",
    "ジヒョ",
    "トワイスのジヒョ",
    "理由",
    "理由を教えてください",
    "理由が浮かんでこない",
    "英語",
    "英語のレベル",
    "なんとかかんとか",
    "サラサラ",
    "そもそも",
    "そもそも話すこと",
    "自分の意見",
    "理由までちゃんと",
    "自分の中",
    "自分の中で分かってる",
]

# Benchmark-only proper nouns (live defaults must NOT include these)
_TEST01_BENCHMARK_KEYTERMS = (
    "オリエンタル商事",
    "永井",
    "木村",
    "チン",
    "シュウメイ",
    "江藤",
)

# Business Japanese profile — default for live sessions (generic only)
JAPANESE_KEYTERMS_BUSINESS = [
    "お世話になっております",
    "いつもお世話になっております",
    "他社",
    "自社",
    "御社",
    "お客様",
    "紹介",
    "自己紹介",
    "他社紹介",
    "でございます",
    "いらっしゃいます",
    "担当",
    "担当者",
    "担当交代",
    "後任",
    "前任者",
    "恐れ入ります",
    "ご丁寧に",
    "参りました",
    "使役形",
    "させていただきます",
    "改まった表現",
    "このたび",
    "本日",
    "明日",
    "昨日",
    "先日",
    "翌日",
    "先ほど",
    "後ほど",
    "営業部",
    "開発部長",
]

JAPANESE_KEYTERMS_NEUTRAL = [
    "お世話になっております",
    "御社",
    "担当",
    "自己紹介",
]

_ESL_TWICE_STALE_MARKER_TERMS = frozenset(
    {
        "ESL",
        "トワイス",
        "ジヒョ",
        "トワイスのジヒョ",
        "英語のレベル",
        "ディスカッション",
        "尊敬してる人",
        "自分の意見",
        "そもそも話すこと",
    }
)

JAPANESE_KEYTERM_CLASSES: dict[str, str] = {}
for _term in JAPANESE_KEYTERMS_ESL_TWICE:
    if _term in ("トワイス", "ジヒョ", "トワイスのジヒョ"):
        JAPANESE_KEYTERM_CLASSES[_term] = "proper_noun"
    elif _term in ("尊敬してる人", "誰ですかっていう質問", "理由を教えてください"):
        JAPANESE_KEYTERM_CLASSES[_term] = "weak_phrase_hint"
    elif _term in ("なんとかかんとか", "サラサラ"):
        JAPANESE_KEYTERM_CLASSES[_term] = "test_video_hint"
    else:
        JAPANESE_KEYTERM_CLASSES[_term] = "domain_term"
for _term in JAPANESE_KEYTERMS_BUSINESS:
    if _term in ("お世話になっております", "いつもお世話になっております"):
        JAPANESE_KEYTERM_CLASSES[_term] = "meeting_term"
    else:
        JAPANESE_KEYTERM_CLASSES[_term] = "domain_term"
for _term in _TEST01_BENCHMARK_KEYTERMS:
    JAPANESE_KEYTERM_CLASSES[_term] = "proper_noun"
for _term in JAPANESE_KEYTERMS_NEUTRAL:
    JAPANESE_KEYTERM_CLASSES.setdefault(_term, "meeting_term")

# Legacy alias — resolved at runtime via resolve_japanese_keyterms()
JAPANESE_KEYTERMS = list(JAPANESE_KEYTERMS_BUSINESS)

_DEFAULT_JA_BUSINESS_JSON = Path(__file__).resolve().parent / "resources" / "keyterms" / "default_ja_business.json"


def _load_default_ja_business_keyterms() -> list[str]:
    """Prefer JSON resource; fall back to inlined generic list."""
    try:
        if _DEFAULT_JA_BUSINESS_JSON.exists():
            data = json.loads(_DEFAULT_JA_BUSINESS_JSON.read_text(encoding="utf-8"))
            terms = [str(t).strip() for t in (data.get("keyterms") or []) if str(t).strip()]
            if terms:
                return terms
    except Exception:
        pass
    return list(JAPANESE_KEYTERMS_BUSINESS)


def resolve_japanese_keyterms(
    profile: str | None = None,
) -> tuple[list[str], str, list[str]]:
    """Return (keyterms, profile_name, stale_esl_twice_terms_removed)."""
    try:
        from alpha.utils.multidomain_gate_evidence import (
            ACCURACY_PROFILE_DOMAIN_AGNOSTIC,
            is_domain_agnostic_no_hints_active,
        )

        if is_domain_agnostic_no_hints_active():
            return [], ACCURACY_PROFILE_DOMAIN_AGNOSTIC, []
    except Exception:
        pass
    try:
        from alpha.utils.issue12_stage1_runtime import (
            ACCURACY_PROFILE_TARGET_85,
            get_active_japanese_accuracy_profile,
            load_meeting_context_keyterm_strings,
            register_meeting_context_keyterm_classes,
        )

        accuracy_profile = get_active_japanese_accuracy_profile()
        # test01 meeting context is experimental_only and not allowed for multidomain.
        if accuracy_profile == ACCURACY_PROFILE_TARGET_85:
            import os

            if os.environ.get("ALPHA_MULTIDOMAIN_BENCHMARK_MODE", "").strip() in (
                "1",
                "true",
                "yes",
            ):
                return [], KEYTERM_PROFILE_NEUTRAL, []
            register_meeting_context_keyterm_classes()
            terms = load_meeting_context_keyterm_strings()
            return terms, ACCURACY_PROFILE_TARGET_85, []
    except Exception:
        pass

    name = (profile or JAPANESE_KEYTERM_PROFILE or KEYTERM_PROFILE_BUSINESS_JAPANESE).strip()
    if name == KEYTERM_PROFILE_ESL_TWICE_TEST:
        terms = list(JAPANESE_KEYTERMS_ESL_TWICE)
        return terms, name, []
    if name == KEYTERM_PROFILE_NEUTRAL:
        return list(JAPANESE_KEYTERMS_NEUTRAL), name, []
    # default business_japanese — generic only (no test01 names)
    terms = _load_default_ja_business_keyterms()
    terms = [t for t in terms if t not in _TEST01_BENCHMARK_KEYTERMS]
    removed = [t for t in _ESL_TWICE_STALE_MARKER_TERMS if t not in terms]
    return terms, KEYTERM_PROFILE_BUSINESS_JAPANESE, removed

JAPANESE_STANDALONE_NO_MERGE = [
    "こんにちは",
    "こんばんは",
    "おはようございます",
    "ありがとうございます",
    "よろしくお願いします",
    "どうぞよろしくお願いします",
    "はい",
    "いいえ",
    "大丈夫です",
]

JAPANESE_COMPOUND_ENDINGS = [
    "音",
    "音声",
    "日本語の音",
    "日本語の音声",
]

JAPANESE_COMPOUND_STARTS = [
    "声",
    "認識",
    "認識を",
    "音声認識",
]

JAPANESE_KNOWN_TERM_CORRECTIONS = {
    "タリクルリスラム": "タリクルイスラム",
    "グラデシュ": "バングラデシュ",
    "音声認識をテストとしています": "音声認識をテストしています",
}

# Deepgram linear16 mono 16 kHz stream expectations
DEEPGRAM_BYTES_PER_SECOND = 32000  # 16000 samples/s * 2 bytes
DEEPGRAM_EXPECTED_KBPS = 256
DEEPGRAM_KBPS_MIN = 230
DEEPGRAM_KBPS_MAX = 290

COMPACT_BREAKPOINT = 900

# Phase 1 active UI scope — English/Japanese only (CN/RU archived as inactive_future)
SOURCE_LANGUAGES = [
    "English",
    "Japanese",
]

TARGET_LANGUAGES = [
    "English",
    "Japanese",
]
